version: "3.9"
services:
  ros2:
    build: .
    network_mode: host
    ipc: host
    volumes:
      - /home/robo/spot_micro:/home/ros
    devices:
      - /dev/i2c-1        # for RPi I2C
      - /dev/video0
      - /dev/gpiomem      # for rpi.gpio
      - /dev/input/js0    # for gamepad
      - /dev/input/event0 # for gamepad
      - /dev/input/event1 # for gamepad
      - /dev/input/event2 # for gamepad
#      - /dev/ttyUSB0:/dev/ttyUSB0
    tty: true
#    environment:
#      - DISPLAY
